
###Get Menu
GET http://localhost:3000/api/v1/menu

###Create Menu
POST http://localhost:3000/api/v1/menu
Content-Type: application/json

{
    "name": "test menu",
    "price": 100,
    "quantity": 10,
    "category": "main",
    "active_status": true
}