
###Get Menu
GET http://localhost:5000/api/v1/menu

###Create Menu
POST http://localhost:5000/api/v1/menu
Content-Type: application/json

{
    "name": "test menu",
    "price": 100,
    "quantity": 10,
    "category": "main",
    "active_status": true
}


###update Menu
PUT  http://localhost:5000/api/v1/menu/
Content-Type: application/json

{
    "name": "test menu",
    "price": 100,
    "quantity": 10,
    "category": "main",
    "active_status": true
}

###delete Menu
DELETE  http://localhost:3000/api/v1/menu/
Content-Type: application/json

{
    "name": "test menu",
    "price": 100,
    "quantity": 10,
    "category": "main",
    "active_status": true
}




###Get promotion
GET http://localhost:3000/api/v1/promotion

###Create promotion
POST http://localhost:3000/api/v1/promotion
Content-Type: application/json

{
    "name": "test promotion",
    "price": 100,
    "quantity": 10,
    "category": "main",
    "active_status": true
}
